function handleErr (err) {
    throw err;
}